# .github/workflows/triage.yml

name: 'AI Issue Triage'

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      # THE FIX IS HERE: This is the essential step I missed.
      # It checks out your repository's code onto the runner.
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Triage Script
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIAGE_API_URL: "https://khush25-issue-triage-api.hf.space/triage" # Make sure this URL is correct

        run: |
          pip install requests
          python .github/workflows/triage.py