name: 'AI Issue Triage'

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Triage Issue
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIAGE_API_URL: "https://khush25-issue-triage-api.hf.space/triage"
        
        run: |
          echo "INFO: Preparing JSON payload..."
          JSON_PAYLOAD=$(jq -n \
                          --arg title "$ISSUE_TITLE" \
                          --arg body "$ISSUE_BODY" \
                          '{title: $title, body: $body}')

          echo "INFO: Calling the prediction API..."
          API_RESPONSE=$(curl -s -X POST \
                               -H "Content-Type: application/json" \
                               -d "$JSON_PAYLOAD" \
                               "$TRIAGE_API_URL")
          echo "INFO: API responded with: $API_RESPONSE"

          PREDICTED_LABEL=$(echo $API_RESPONSE | jq -r .predicted_label)
          echo "INFO: Extracted label: $PREDICTED_LABEL"

          # --- THE FIX IS HERE: Using a direct API call to apply the label ---
          if [[ -n "$PREDICTED_LABEL" && "$PREDICTED_LABEL" != "null" ]]; then
            echo "INFO: Applying label '${PREDICTED_LABEL}' to issue #${ISSUE_NUMBER}..."
            
            # This is a more robust way to apply a label
            curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/labels" \
            -d "{\"labels\":[\"$PREDICTED_LABEL\"]}"

            echo "INFO: Labeling command sent successfully."
          else
            echo "WARNING: No valid label was predicted by the API."
          fi